### PR TITLE
Adding basic test suite

### PR DESCRIPTION
**Pull request by oldremez**
This PR is still WIP. I'm going to polish it a lot, however, would love to get some feedback on the approach from the maintainers if it's possible.

The proposed solution (as described in issue #40) is to add support for S3-compatible solutions and put together a docker container with:
1. minio (S3-compatible self-hosted solution)
2. gaiad
3. multisig
4. scripts with testing scenarios

That's already done and the first scenario (transfer assets from multisig) passes. However, the current implementation is far from being production-ready because of multiple issues.

Known issues:
1. docker image is too big (around 3 GB 😅) and needs to be optimized a lot
2. testing scenario is just a shell script and needs to be wrapped with some testing framework
3. a lot of things are hard-coded
4. different tricks to make it work ("sleep" instructions and so on)

The implementation barely touches the existing codebase (adding a single field at config and handling it in aws.go). Everything test-related is a new set of files.

### CODE REVIEW

**Comment by oldremez** [comment]
A short update on the progress so far:
1. Docker image size has been optimized with the multi-stage build mechanic
2. Added bats test framework to wrap testing scenarios
3. Code refactored a bit to have less hardcoded stuff
4. Sleep instructions have been replaced with waiting for events to happen

The code still needs to be polished a bit more.

**Comment by andynog** [comment]
Thanks @oldremez for submitting this draft PR. Sorry for the late reply, I was away on vacation. But I'll be glad to track and review this PR once it is ready. Thanks again.

**Comment by oldremez** [comment]
Hey, sorry for disappearing! I'm back and happy to proceed to work on this PR. Basically, I mostly finished it and now just polishing stuff a bit. I've implemented three basic tests (simple successful sending, failing if there are not enough signatures for 2/3 multisig, and failing if there are not enough signatures for 3/4 multisig (this one fails as expected since there is [2 is hardcoded](https://github.com/informalsystems/multisig/blob/b1313954e334500fdb5649064ea72433ea222e64/main.go#L791))).

What is really not handy and blocks me to write more tests is the lack of possibility to provide a path to config via command line argument. Without that, one is forced to make different configs for tests in different directories and switch between them across the test suit which looks bad.

Not sure if it's a good idea to add the ability to pass the config path in this PR though. This way leads to adding a lot of stuff in a single PR so I'd propose to finish the test kit and switch to related things further.

Hope to finalize my work this weekend.

**Comment by oldremez** [comment]
Okay, I think it's done, at least my eyes get glazed over enough to miss any important issues in the code if they're present.

@andynog would love to get a review from you when it's possible, thanks!

**Comment by andynog** [comment]
> Okay, I think it's done, at least my eyes get glazed over enough to miss any important issues in the code if they're present.
> 
> @andynog would love to get a review from you when it's possible, thanks!

Thanks @oldremez I'll review it tomorrow. Thanks again.

**Comment by oldremez** [comment]
By the way, I managed to add the possibility to specify the path to the config file via the command line flag. The current implementation (with tests!) is [here](https://github.com/oldremez/multisig/tree/feat/config-arg).
Apart from specifying the config path via command line flag, I also added an ability to use `~/.multisig/config.toml` as the default config (it's covered with the tests, too).
I also adjusted existing tests to use explicitly specified config paths to avoid weird `cd`s during the tests, and to add more transparency.
After merging this PR I'll be able to prepare a new one with described functionality.

cc @andynog

**Review by andynog — APPROVED** [review]
I think this is a good implementation of doing an end to end testing and have different tests. Also like the idea of using docker containers. Maybe one idea is to include this test as a Github Action that could be triggered during PR mergers. I also like the new way of using a local S3 (minio) in the tests and also having a possibility to use a S3 compatible service in the future. LGTM

**Comment by andynog** [comment]
> By the way, I managed to add the possibility to specify the path to the config file via the command line flag. The current implementation (with tests!) is [here](https://github.com/oldremez/multisig/tree/feat/config-arg). Apart from specifying the config path via command line flag, I also added an ability to use `~/.multisig/config.toml` as the default config (it's covered with the tests, too), as [requested in the README](https://github.com/informalsystems/multisig/blob/b1313954e334500fdb5649064ea72433ea222e64/README.md?plain=1#L313). I also adjusted existing tests to use explicitly specified config paths to avoid weird `cd`s during the tests, and to add more transparency. Still, it's fully backward-compatible, so any user with a local `config.toml` file will get the same behavior as before. After merging this PR I'll be able to prepare a new one with described functionality.
> 
> cc @andynog

I think the idea of having a way to specify a config location or using a default ($HOME/.multisig/config.toml) nice but it should also be backward compatible so if not specified as a flag and not in the $HOME folder then use the local one. But this can be a future PR. I'm merging some PRs today so please make sure you can catch up with the new changes before submitting the config PR. Thanks again. Great job.

**Pull request merged**
