### PR TITLE
Improving config management

### PR DESCRIPTION
**Pull request by oldremez**
The changes allow to
1. Use any config specified by the `--config` flag
2. Use `~/.multisig/config.toml` as a default config if the config is not specified explicitly and not present in the current dir

As highlighted in [the comment on the previous PR](https://github.com/informalsystems/multisig/pull/41#issuecomment-1221047210), such behavior is fully backward compatible. So, if the config is present in the current dir, everything works as expected (global config is ignored in this case).

Such a feature may simplify the usage of a tool and it definitely simplifies the testing process which is reflected in the PR already (we can use different configs during the testing process without needing of hopping across different dirs).

PR is a draft because I want to take a look at the code once again (maybe more proper error handling is required, I dunno). Also, I want to check if anything broke after merging recently added features into my local branch (it shouldn't because the project builds and dummy tests pass but I just want to double check/add more tests there to be sure).

### CODE REVIEW

**Comment by andynog** [comment]
Thanks @oldremez, please let me know when the PR is ready for review.

**Comment by oldremez** [comment]
Oh, great! Basically, everything looks to work with recent features added. I tried to take a look if I could refactor flag management a bit (I don't really like the way of using global variables and stuff) but haven't managed to come up with a better solution so far.

The other question I haven't touched on is the creation of a global config. So, the global config is used if it has been created manually but it isn't created by the `go install`, or `multisig` itself, or something.

I'm pretty sure those are not blockers for adding the feature, especially right before release (don't want to make major changes right before).

I'll make a last look at the current implementation today with no intent to make any major changes and will move PR from the "Draft" state if everything is ok for me.

**Comment by andynog** [comment]
> Oh, great! Basically, everything looks to work with recent features added. I tried to take a look if I could refactor flag management a bit (I don't really like the way of using global variables and stuff) but haven't managed to come up with a better solution so far.
> 
> The other question I haven't touched on is the creation of a global config. So, the global config is used if it has been created manually but it isn't created by the `go install`, or `multisig` itself, or something.
> 
> I'm pretty sure those are not blockers for adding the feature, especially right before release (don't want to make major changes right before).
> 
> I'll make a last look at the current implementation today with no intent to make any major changes and will move PR from the "Draft" state if everything is ok for me.

Happy to review if it is ready

**Comment by oldremez** [comment]
@andynog, sorry for the late answer. Yeah, looks finished from my side, just added a couple of things (bumped forgotten version, added comments, and adjusted the TODO section a bit to reflect some recent changes/requirements).

**Review by andynog — APPROVED** [review]
The changes look good to me. Tested the different config location scenarios and seems to be working well. Thanks!

**Pull request merged**
